name: cloud_gallery
description: "Cloud File Manager that works with various cloud providers."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # Modules
  data:
    path: ../data
  style:
    path: ../style

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14
  fluttertoast: ^8.2.8
  cached_network_image: ^3.4.1
  video_player: ^2.9.2
  visibility_detector: ^0.4.0+2
  flutter_displaymode: ^0.6.0

  # state management
  flutter_riverpod: ^2.6.1

  # permission
  permission_handler: ^11.3.1

  # navigation
  go_router: ^14.4.1

  # auth
  google_sign_in: ^6.2.2

  # core
  firebase_core: ^3.7.0
  collection: ^1.18.0
  path_provider: ^2.1.5
  dio: ^5.7.0
  flutter_local_notifications: ^18.0.1
  share_plus: ^10.1.2
  webview_flutter: ^4.10.0

  photo_manager: ^3.6.2
  photo_manager_image_provider: ^2.2.0

  # storage
  shared_preferences: ^2.3.3

  # code generation
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # lints
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.2

  # code generation
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/icons/