name: cloud_gallery
description: "Cloud File Manager that works with various cloud providers."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # Modules
  data:
    path: ../data
  style:
    path: ../style

  # UI
  cupertino_icons: ^1.0.2

  # state management
  flutter_riverpod: ^2.4.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  # lints
  flutter_lints: ^2.0.0
  riverpod_lint: ^2.1.1

  # code generation
  build_runner: ^2.3.3
  freezed: ^2.4.6


flutter:
  uses-material-design: true
  generate: true