name: cloud_gallery
description: "Cloud File Manager that works with various cloud providers."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # Modules
  data:
    path: ../data
  style:
    path: ../style

  #Services
  workmanager: ^0.5.2

  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  cached_network_image: ^3.3.1
  video_player: ^2.8.3
  visibility_detector: ^0.4.0+2
  flutter_displaymode: ^0.6.0

  # state management
  flutter_riverpod: ^2.4.9

  # permission
  permission_handler: ^11.3.0

  # navigation
  go_router: ^13.0.1

  # auth
  google_sign_in: ^6.2.1

  # core
  firebase_core: ^2.24.2
  collection: ^1.18.0

  # storage
  shared_preferences: ^2.2.2

  # code generation
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # lints
  flutter_lints: ^2.0.0
  riverpod_lint: ^2.1.1

  # code generation
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/icons/