name: Analyze

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: subosito/flutter-action@v2
        name: Set up Flutter SDK
        with:
          flutter-version: latest
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Lint test
        run: dart analyze --fatal-infos
