name: Analyze

on: push

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Retrieve the secret and decode it to a file
        env:
          FIREBASE_OPTIONS_BASE64: ${{ secrets.FIREBASE_OPTIONS_BASE64 }}
          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
          GOOGLE_SERVICE_INFO_PLIST_BASE64: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_BASE64 }}
          FIREBASE_APP_ID_FILE_JSON_BASE64: ${{ secrets.FIREBASE_APP_ID_FILE_JSON_BASE64 }}
          FIREBASE_JSON_BASE64: ${{ secrets.FIREBASE_JSON_BASE64 }}
          APP_SECRETS_BASE64: ${{ secrets.APP_SECRETS_BASE64 }}

        run: |
          cd app
          echo $FIREBASE_OPTIONS_BASE64 | base64 -di > lib/firebase_options.dart
          echo $GOOGLE_SERVICES_JSON_BASE64 | base64 -di > android/app/google-services.json
          echo $GOOGLE_SERVICE_INFO_PLIST_BASE64 | base64 --decode > ios/Runner/GoogleService-Info.plist
          echo $FIREBASE_APP_ID_FILE_JSON_BASE64 | base64 --decode > ios/firebase_app_id_file.json
          echo $FIREBASE_JSON_BASE64 | base64 --decode > firebase.json
          cd ../data
          echo $APP_SECRETS_BASE64 | base64 --decode > lib/apis/network/secrets.dart

      - name: Install dependencies
        run: |
          cd app
          flutter clean
          flutter pub get
          
          cd ../data
          flutter clean
          flutter pub get
          
          cd ../style
          flutter clean
          flutter pub get
          
          cd ..

      - name: Lint test
        run: |
          cd app
          dart format . --set-exit-if-changed
          dart analyze --fatal-infos
          
          cd ../data
          dart format . --set-exit-if-changed
          dart analyze --fatal-infos
          
          cd ../style
          dart format . --set-exit-if-changed
          dart analyze --fatal-infos
          
          cd ..
        
